"""reference/icons.md: generated by research/tools/gen_icons.py from the cached Divi build's icon list."""
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from _paths import SKILL, TOOLS
from divi_checks_values import value_problems
from divi_schema import load_schema

import fetch_divi

ICONS_MD = SKILL / "reference" / "icons.md"
VALUE_RE = re.compile(r"`(&#x[0-9a-fA-F]+;\|\|(?:divi|fa)\|\|\d{3})`")


def doc_version():
    m = re.search(r"Divi (\d+(?:\.\d+)+)", ICONS_MD.read_text(encoding="utf-8"))
    return m.group(1) if m else None


class IconsDocTest(unittest.TestCase):
    def test_every_value_passes_the_validators_icon_check(self):
        text = ICONS_MD.read_text(encoding="utf-8")
        values = VALUE_RE.findall(text)
        self.assertGreater(len(values), 1500)
        res = load_schema().module("et_pb_blurb").resolve("font_icon")
        bad = [v for v in set(values) if value_problems(res, "font_icon", v)]
        self.assertEqual(bad, [])

    def test_every_icon_line_carries_a_value(self):
        # a list line per icon: "- `VALUE` name (family, style) — search terms"
        lines = [l for l in ICONS_MD.read_text(encoding="utf-8").splitlines() if l.startswith("- `&#x")]
        self.assertEqual(len(lines), len(VALUE_RE.findall(ICONS_MD.read_text(encoding="utf-8"))))

    def test_common_icons_come_first(self):
        text = ICONS_MD.read_text(encoding="utf-8")
        self.assertLess(text.index("## Common icons"), text.index("## Divi icon font"))
        self.assertIn("`&#xf095;||fa||900` phone", text)

    def test_regenerates_deterministically(self):
        version = doc_version()
        theme = fetch_divi.theme_dir(version) if version else None
        if theme is None:
            self.skipTest(f"Divi {version} not cached (python3 scripts/preview.py fetch-divi {version})")
        with tempfile.TemporaryDirectory() as tmp:
            outs = []
            for n in (1, 2):
                out = Path(tmp) / f"icons{n}.md"
                proc = subprocess.run([sys.executable, str(TOOLS / "gen_icons.py"), "--divi", str(theme), "--out", str(out)],
                                      capture_output=True, text=True)
                self.assertEqual(proc.returncode, 0, proc.stderr)
                outs.append(out.read_bytes())
        self.assertEqual(outs[0], outs[1])
        self.assertEqual(outs[0], ICONS_MD.read_bytes())


if __name__ == "__main__":
    unittest.main()
