"""Task 28: reference/preview.md's supported-modules table must match divi_render's registry.

The table is generated by research/tools/gen_preview_module_table.py from
divi_render.SUPPORTED_MODULES (the @register(...) handler map). This test is the drift guard: if
a module handler is added/removed/renamed without re-running that script, the doc goes stale
silently -- these tests catch it instead.
"""
import re
import unittest

from _paths import SKILL, TOOLS  # noqa: F401  (TOOLS import puts research/tools on sys.path)

import divi_render as dr
from gen_preview_module_table import BEGIN, END, module_table

PREVIEW_MD = SKILL / "reference" / "preview.md"


def _current_table() -> str:
    text = PREVIEW_MD.read_text(encoding="utf-8")
    _, rest = text.split(BEGIN, 1)
    current, _ = rest.split(END, 1)
    return current.strip()


class PreviewDocsTest(unittest.TestCase):
    def test_markers_are_present(self):
        text = PREVIEW_MD.read_text(encoding="utf-8")
        self.assertIn(BEGIN, text)
        self.assertIn(END, text)

    def test_module_table_matches_the_generator(self):
        self.assertEqual(_current_table(), module_table().strip(),
                          "reference/preview.md's supported-modules table is out of date: run "
                          "python3 research/tools/gen_preview_module_table.py")

    def test_table_tags_are_exactly_the_registry(self):
        tags = set(re.findall(r"`(et_pb_[a-z_]+)`", _current_table()))
        self.assertEqual(tags, set(dr.SUPPORTED_MODULES))

    def test_unsupported_examples_outside_the_table_are_not_in_the_registry(self):
        # et_pb_search / et_pb_login are called out in prose as *not* rendered by the Python
        # preview; if either is ever ported, this catches the doc claiming otherwise.
        for tag in ("et_pb_search", "et_pb_login"):
            with self.subTest(tag=tag):
                self.assertNotIn(tag, dr.SUPPORTED_MODULES)


if __name__ == "__main__":
    unittest.main()
